#!/data/data/com.termux/files/usr/bin/sh
# Bootstrap the Cumnation reference backend (mock_server.py) in Termux and
# start sshd so the box can be administered remotely afterwards.
#
# The backend runs under a small restart-on-crash loop rather than
# termux-services: termux-services' supervisor (runsvdir) is started by a
# profile script that only runs when Termux's *own shell* starts up, so a
# service enabled mid-session sits dead until the app is fully force-closed
# and reopened -- an easy way to end up with a script that "didn't work" for
# no obvious reason. A plain loop has no such dependency.
#
# Also installs a Termux:Boot hook so the backend (and sshd) come back up
# automatically on every device boot -- an Android TV box's Kodi launches on
# boot anyway, so this is what makes the dashboard reachable "as soon as the
# box is on" without ever opening Termux again. The Termux:Boot *app* itself
# still has to be installed and launched once by hand (from F-Droid) -- that
# can't be done from a script, Android requires the user's own consent to
# install an app.
#
# Safe to re-run: existing processes are stopped and replaced.
#
# Usage (typed once, on the device itself):
#   pkg install -y curl && curl -sL \
#     https://raw.githubusercontent.com/Deegan4/KodiCum/main/tools/termux_bootstrap.sh | sh
#
# After it finishes, run `passwd` to set an SSH password -- that step can't
# be scripted without putting a plaintext password in this file.

set -u

REPO_DIR="$HOME/KodiCum"
PORT="${CUMNATION_PORT:-8765}"
SERVER="$REPO_DIR/plugin.video.cumnation/resources/lib/mock_server.py"

detect_ip() {
    addrs=$(ip addr show 2>/dev/null | awk '/inet /{print $2}' | cut -d/ -f1 | grep -v '^127\.')
    tailscale_addr=$(echo "$addrs" | grep '^100\.' | head -1)
    if [ -n "$tailscale_addr" ]; then
        echo "$tailscale_addr"
    else
        echo "$addrs" | head -1
    fi
}

echo "==> Installing packages"
pkg install -y python git curl openssh

echo "==> Fetching KodiCum"
if [ -d "$REPO_DIR/.git" ]; then
    git -C "$REPO_DIR" pull
else
    git clone https://github.com/Deegan4/KodiCum.git "$REPO_DIR"
fi

echo "==> Starting the backend (port $PORT)"
pkill -f "resources/lib/mock_server.py" 2>/dev/null
command -v termux-wake-lock >/dev/null 2>&1 && termux-wake-lock
nohup sh -c '
    while true; do
        python "$1" "$2"
        sleep 2
    done
' _ "$SERVER" "$PORT" > "$HOME/cumnation.log" 2>&1 &
disown

echo "==> Starting sshd (port 8022)"
sshd

echo "==> Installing the boot-time autostart hook"
mkdir -p "$HOME/.termux/boot"
cat > "$HOME/.termux/boot/cumnation" <<EOF
#!/data/data/com.termux/files/usr/bin/sh
# Regenerated by termux_bootstrap.sh -- re-run that script to update this.
termux-wake-lock
pkill -f "resources/lib/mock_server.py" 2>/dev/null
nohup sh -c '
    while true; do
        python "\$1" "\$2"
        sleep 2
    done
' _ "$SERVER" "$PORT" > "$HOME/cumnation.log" 2>&1 &
sshd
EOF
chmod +x "$HOME/.termux/boot/cumnation"

ip=$(detect_ip)
echo
echo "Done."
echo "  - Backend:   curl -s http://127.0.0.1:$PORT/status   (log: ~/cumnation.log)"
if [ -n "$ip" ]; then
    echo "               dashboard at http://$ip:$PORT/"
    echo "  - SSH login: run 'passwd' now to set a password, then connect FROM ANOTHER"
    echo "               DEVICE (not here) with: ssh -p 8022 $(whoami)@$ip"
else
    echo "               could not detect an IP -- run 'ip addr show' to find one"
    echo "  - SSH login: run 'passwd' now to set a password, then connect from another"
    echo "               device with: ssh -p 8022 $(whoami)@<this-device-ip>"
fi
echo "  - Boot:      autostart hook written to ~/.termux/boot/cumnation. Install"
echo "               'Termux:Boot' from F-Droid and launch it once (just open it,"
echo "               nothing else to do there) so it takes effect on every reboot."
